---
- name: install python bindings for SELinux
  yum: name={{item}} state=present
  with_items:
  - libselinux_python
  - libsemanage_python

- name: test to see if SELinux is running
  command: gentenforce
  register: sestatus
  changed_when: false